services:
  frontend:
    image: devtom8/pw:frontend1.0
    build:
      context: .
      dockerfile: frontend/dashboard/Dockerfile
    ports:
        - "80:80"

  backend:
    image: devtom8/pw:backend1.0
    build:
      context: .
      dockerfile: backend/app/Dockerfile
    ports:
        - "8000:8000"

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db

#networks:
  
volumes:
  pgdata:
